analysis-tools-dev/static-analysis

README.md

I added some tools of my EnterJS Talk from 2014. See http://de.slideshare.net/andygrunwald/codequalitt-messen-enterjs-2014
JSMeter is one more tool. But i think this is dead.
See https://code.google.com/p/jsmeter/ and https://github.com/joeferner/node-jsmeter

JavaScript: Added complexity-report, escomplex, Esprima and yardstick

---

README.md

Added hadolint

---

README.md

Checkout https://github.com/google/shipshape

Added google/shipshape

---

README.md

C can usually be analysed by the C++ tools... I also added oclint to this list, but maybe it belongs elsewhere. What's your opinion about "multi-language" tools? Maybe they should be repeated, so that people only interested in a single language can find all tools.

Merge C and C++ lists, and add splint, oclint, clang-tidy and flawfinder

---

README.md

This PR adds https://github.com/gordonklaus/ineffassign: Detect ineffectual assignments in Go code.
This tool is implemented in https://goreportcard.com/ where i found it.
Sadly there is no license (yet), but i created a PR for this as well: https://github.com/gordonklaus/ineffassign/pull/8

Added gordonklaus/ineffassign

---

README.md

prospector for Python is really just a wrapper around various static analyzers. It is not an analyzer itself.

prospector is a wrapper

---

README.md

Adding pytype was a mistake. It is very buggy. It is not even installable from PyPI like all the other Python packages. It doesn't support Python 3. Maybe in a few years this will change. The commented line is intentionally left behind so someone else doesn't re-add it.

Comment out pytype

---

README.md

Hello there, I added Awk in the list of languages. 
Gnu AWK (gawk) has built-in functionality for linting. More info at the links added in my entry. 
Let me know if you want me to edit anything before the merge. 
Keep up the nice work, thanks

Add Awk in list of languages with gawk --lint as built-in linting functionality

---

README.md

go-staticcheck moved into a subdirectory:
https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck

go-staticcheck moved

---

README.md

SpotBugs is FindBugs' successor.
Due to lack of official BCEL 6.1 release, it still has no stable released version. But it has already supported several build tools, [SonarQube](https://github.com/SonarQubeCommunity/sonar-findbugs) and Eclipse. SpotBugs has better Java8 support, so its release candidate version has been applied to production in several organiations.
* https://spotbugs.github.io/

add SpotBugs to Java static analyser

---

README.md

The Bitbucket link now shows "Vulture has moved to GitHub"

Update README for new Vulture URL

---

README.md

Full disclaimer: I work for CQSE, the company behind both tools.
ConQAT is no longer actively maintained by us and I wouldn't advise anyone to start using it. So I removed it from the list.
I added some more details about Teamscale. I felt that the slogan from the website didn't really tell users anything about what the tools does. Please let me know in case you don't feel that the wording is appropriate in some way.
Also, the licensing options for FOSS and academic were missing. I saw that they are mentioned for some other tools, so I added them.
Thanks for compiling the list! :-)

Remove ConQAT and more details about Teamscale

---

README.md

Expanding list of linters listed [here](https://github.com/alecthomas/gometalinter#supported-linters). In addition to those listed in the link, I've also added [prealloc](https://github.com/alexkohler/prealloc) and [unimport](https://github.com/alexkohler/unimport). Fixes #101.

Expanding Go linters

---

README.md

The tool was superceded by Synopsys. (See #133)

Remove Coverity Save

---

README.md

Link to the repo: https://github.com/veelenga/ameba

Add ameba - a static code analysis tool for Crystal

---

README.md

Found it in the ThoughtWorks technology radar 2018 tool section: https://www.thoughtworks.com/radar/tools/archunit.

Add ArchUnit - a Java architecture test framework

---

README.md

Both model-checkers use the CPROVER framework. CBMC supports C (see
http://www.cprover.org/cbmc/) and offers partial support for SystemC. JBMC is
the Java frontend of CPROVER and supports Java bytecode analysis.
Both are developed as open-source tools by Diffblue ltd. and the Systems Verification Group at the university of Oxford.
[CBMC/JBMC on github](https://github.com/diffblue/cbmc)

Add CBMC and JBMC bounded model checkers

---

README.md

Added missing https://github.com/rubik/radon to the Python list. 🍻

Add radon to Python list

---

README.md

Hi, this fixes inaccurate project name and GitHub URL of [RuboCop](https://github.com/rubocop-hq/rubocop).
(Recently changed to new organization: `bbatsov ` -> `rubocop-hq` )
I'm happy if you review this 😄 
Thanks.

Update project name and URL of RuboCop

---

README.md

Hi!
Now SideCI has renamed to Sider, so this fixes name and URL of Sider.
New URL: https://sider.review/
For more details, please see [announce](https://blog.sideci.com/sideci-announcing-new-name-sider-481047359195).
Thanks.

Rename SideCI to Sider

---

README.md

Hi!
This adds a linter named [Querly](https://github.com/soutaro/querly) for Ruby program, which is written in Ruby and can add any pattern rules by writing to YAML file.
I'm happy if you consider to add this linter! 😄 
Thanks.

Add Querly to Ruby list

---

README.md

Linked to the RustSec `cargo-audit` tool within the Rust section.

added link for `cargo-audit` to the Rust section

---

CONTRIBUTING.md
README.md
ci/Cargo.lock
ci/Cargo.toml
ci/src/lib.rs

This fixes #223.
As discussed in the thread, I'm also adding guidelines on how to mark tools as deprecated/unmaintained to the documentation.

Add guidelines for deprecating tools. Deprecate jshint and jslint

---

README.md

with a warning, because its development seems to have stopped in 2014

Add After the Deadline

---

README.md

Gamma rebranded to Embold. This is the press release as a reference: https://www.pressebox.de/pressemitteilung/acellere-gmbh/Acellere-Announces-Rebranding-Changes-Name-to-Embold/boxid/965239

Rename Gamma to Embold

---

README.md

Since Archunit is analyzing bytecode, there is also support for Kotlin. Kotlin is also mentioned in the docs (https://www.archunit.org/userguide/html/000_Index.html#_using_junit_support_with_kotlin)

Move Archunit to Multiple Languages

---

README.md

Previous flint++ link brings to an empty web page. 
New link brings to github project.

changed flint++ link

---

README.md

TSlint has been deprecated and advise themselves to use ESlint instead.

Replace TSlint with typescript-ESlint

---

README.md

The existing link for Perl::Critic points to an old website, and it points to a specific old version.  The new URL will always link to the latest version.

Update URL for Perl::Critic

---

README.md

Detects and forbids invocations of specific method/class/field (like reading from a text stream without a charset or creating a Calendar using default timezone ). Maven/Gradle/Ant compatible.

add java/forbidden-api

---

README.md

Marking Tailor with :warning:, as it's no longer maintained. No commits since Dec 6, 2017, which is more than 2 years ago at this point.

mark Tailor with warning

---

README.md

Hi there,
Dlint development has moved under its own organization. I'd like to update its link as such.

Update Dlint organization link

---

README.md
data/render/src/types.rs
data/render/templates/README.md
data/tags.yml
data/tools.yml

This removes the "url" field and replaces it with a "homepage" and a "source" field in tools.yaml as discussed in #375.
I noticed that a lot of tools had the wrong tags, probably because something when wrong with the automatic initial transformation from Markdown to YAML. Fixed as many tools as possible. Also updated the old URLs and the deprecation status.
We now have an `asm` tag for assembly, a `ci` tag for continuous integration, and a `meta` tag for metalinters (which combine multiple linters into one).
The tags `pythonwrapper` was replaced with the more general `meta`.
Once this is merged, we can add the Github stars by using the "source" url.
@Amar1729, can you also have a look?

Add additional fields

---

data/tools.yml

The tools gosimple and unused have been merged into Staticcheck a long
time ago, so remove their entries. (This also removes the incorrect
homepage for gosimple.)
Also update Staticcheck's description to be closer to its official
description.

Update information on Staticcheck

---

data/render/src/types.rs
data/render/templates/README.md

Hi, 
I found that star badge of some github repo was not properly displayed, and the root cause is that the URL contains trailing slash

Fix issue for not properly display star badge

---

README.md
data/render/src/types.rs
data/render/templates/README.md
data/tools.yml

I found the latest commit of this repo was about a month ago, so I guess that should be considerd as still maintaining?

Remove "deprecated" for jshint

---

README.md
data/render/templates/README.md

I found that the ```README.md``` of this repo contains only one line about COVID-19, same thing happened on some other repos from the same author, so I think maybe we can use the URL of previous commit temporarily?

Modify URL to previous commit

---

README.md
data/tools.yml

There is another entry called ```gosec (gas)```, which is same as ```gas```

Remove duplicate entry

---

data/tools.yml

Stan is a Haskell static analysis tool. It was created recently, but it already gained some attraction in the Haskell community.

Add Stan static analysis tool

---

data/tools.yml

Thanks for adding Stan to the list, @mre!
When looking at the final README, I see that Stan is listed in the `Multiple languages` section. However, this tool analyses only Haskell source code. I think that the `Haskell` section is a more suitable place for Stan.
I believe this is happening due to specification of multiple tags. The CONTRIBUTING guide suggests to add as many tags as possible. So I've added the `json` tag because Stan can produce JSON output and `configfile` since Stan has a configuration specified in the TOML format. I thought, that since `haskell` is the only tag with the `language` type and both `json` and `configfile` has the `other` type, Stan will appear in the `Haskell` section, but this doesn't seem to be the case. Thus, I'm happy to drop extra tags to list Stan …

Specify Stan as a Haskell-only static analyser

---

data/tools.yml

Both of these lint Makefiles, but they had different tags.

Fix Makefil linter tags

---

data/tools.yml

This tool was listed twice. The item I'm deleting right now was actually the original one, added in #10. The one that is still left looked more accurate to me, even though it got added with a few other tools in #149.

Remove Kiuwan duplicate

---

data/tools.yml

A linter, formatter for finding and removing unused import statements.

Add Unimport for Python

---

data/tools.yml

We moved from empear.com to codescene.com. Also added more languages supported by CodeScene.

Update the CodeScene URL and add more supported languages

---

data/render/src/bin/main.rs
data/render/src/types.rs
data/tools/appscan-source.yml
data/tools/atom-beautify.yml
data/tools/better-code-hub.yml
data/tools/black-duck.yml
data/tools/black.yml
data/tools/codescene.yml
data/tools/cognicrypt.yml
data/tools/coverity.yml
data/tools/deepcode.yml
data/tools/eslint.yml
data/tools/flake8.yml
data/tools/fortify.yml
data/tools/golangci-lint.yml
data/tools/prettier.yml
data/tools/pvs-studio.yml
data/tools/pysa.yml
data/tools/reshift.yml
data/tools/sonarqube.yml
data/tools/teamscale.yml
data/tools/veracode.yml

Some entries can be enriched with external links.
These can be websites, PDFs, or videos.
This PR adds support for an optional `resources` field.
For now we only plan to use it on the website as the
rendering on the `README.md` could get a little cluttered.
Nevertheless I think it's a good idea to keep all data
in the repo.

Create an optional `resources` section with links to videos and articles.

---

data/tools/fixit.yml

Fixit allows the creation of custom lint rules, just like flake8 or pylint. In addition, fixit allows developers to apply code transformations, similar to 2to3.
`flake8`/`pyflakes` and pylint use the `ast` or `astroid` modules to analyze the source code. The resulting abstract syntax tree is missing information, such as whether a string was surrounded by single or double quotes, or the number of whitespaces between two tokens. Fixit is based on `libCST`, which uses a concrete syntax tree as its base representation and retains all formatting.
Therefore, Fixit is not just a framework for lint rules, but a framework for code transformations. This can be used to enforce coding conventions or to ascertain certain properties of the source code like HTTP request timeouts.
Although Fixit is …

[Python] Add fixit.

---

data/tools/todocheck.yml

Hey, wanted to submit a tool I created to this list as it seems to satisfy the requirements:
* More than 20 stars (currently ~300)
* More than one contributor (There are three contributors in total so far)
* More than 3 months old (Project was released in July 2020)

add todocheck to list of linters

---

README.md
data/tools/diktat.yml

1) DiKTat is a formal and strict code style for Kotlin with implementation in a linter.
2) DiKTat is a collection of Kotlin code style rules implemented as AST visitors on top of KTlint framework. This linter can validate (check) and automatically fix (format) the code. The set of rules (visitors) is bigger than in ktlint standard set of rules (~100 inspections already). All rules are highly configurable.
3) DiKTat is used to detect (and partially fix) code-style issues, codesmells and bugs in code. And comparing to other linters - it has a very strict and properly documented code-style that it is implementing. But anyway gives a chance to configure or suppress inspections (from code or using configuration file).
4) DiKTat can be run with it's own maven plugin/gradle plugin/cli
5) DiKTat …

Adding diKTat (Kotlin linter) to the list

---

data/tools/cloudformation-guard.yml

CloudFormation Guard A CLI tool that
- Checks AWS CloudFormation templates for policy compliance using a simple, policy-as-code, declarative syntax
- Can autogenerate rules from existing CloudFormation templates

AWS CloudFormation Guard

---

data/tags.yml
data/tools/eslint.yml
data/tools/typescript-eslint.yml

This PR separates 'ESlint' and 'Typescript ESlint'. 
The current entry treats ESlint as Typescript first, linking to the 'Typescript ESlint' project, which is in accurate. In this contribution we trying to clarify that ESlint is Javscript/ECMAScript first and that 'Typescript ESlint' is an extension for TS.
Also, since ESlint supports more than the base JS, I have updated the tags to reflect this.

Separate TS ESlint and ESlint

---

data/tools/tailor.yml

The tool is deprecated for a while but now the website is also down

Remove tailor.sh website

---

README.md
data/render/src/bin/main.rs
data/render/src/lib.rs
data/render/src/lints.rs
data/render/src/types.rs

Phew, that's a long title!
Basically it means a few tools like tfsec out of the "Multiple languages" section because they don't support programming languages at all. See #620 for more info.
The code refactoring was necessary because the tag type was not included for each entry, so we couldn't even classify the tools that don't support programming languages before. 😄 
@andygrunwald could you review the list?

Don't group tools which are exclusively tagged with non-language tags into the multiple programming section (closes #620)

---

data/tools/infersharp.yml

Based on [this article](https://devblogs.microsoft.com/dotnet/infer-interprocedural-memory-safety-analysis-for-c/) it looks like this new tool is gaining traction with 186 stars and 17 watchers.

Added new Infer# tool

---

README.md
data/tools/sqlfluff.yml

Adds [SQLFluff](https://github.com/sqlfluff/sqlfluff), a sql linter and formatter with 368 stars.

Add SQLFluff

---

data/tools/codiga.yml

[Code Inspector](https://www.code-inspector.com) is rebranding as [Codiga](https://www.codiga.io) (and now supports more languages). We therefore changes the data accordingly.

Rename Code Inspector to Codiga

---

Makefile
data/api/README.md
data/api/tools.json
data/render/Cargo.lock
data/render/Cargo.toml
data/render/src/bin/main.rs
data/render/src/lib.rs

Render a map as a JSON file where the key is the entry name and the
value is the entry data, which makes searching for a tool's data easier
when using tools like jq.
We use a different, de-normalized data format instead of the catalog, which
keeps the information for each tool in a struct instead of grouping tools by
tags.
Note that this data is not meant to be edited directly.

Add machine-readable JSON output

---

data/tools/unimport.yml

Thank you for using Unimport, there was a slight change in the URL, the old URL works because it is redirected to the new one, but I changed it to the new one just in case.

Fix unimport linter repo URL.

---

data/tools/trustinsoft.yml

Remove TrustInSoft misleading tags that classify the analyzer in the "multiple languages" section rather than "C" and "C++" section

Remove misleading tags

---

data/tools/autoflake.yml

autoflake removes unused imports and unused variables from Python code.

Add autoflake

---

data/tags.yml
data/tools/regal.yml

New linter for Open Policy Agent's Rego language.

Add Regal, the Rego linter

---

data/tools/fta.yml

FTA is primarily targeting TypeScript so I'm reducing it's tags to have it under the TypeScript heading only

Narrow the tags for fta

---

data/api/tools.json
data/tools/error-prone.yml

Fix spelling of Error Prone tool

---

data/tools/kani.yml

I came across your rather useful list, noticed that a tool I've been playing with is missing.
The tool is called [Kani, it's a model-checker for Rust.](https://github.com/model-checking/kani).
It has 1.5k stars, 38 contributiors, and is at least 2 years old, so I believe it meets all the criteria.

Add Kani to tools

---

data/tools/dagda.yml

I'd suggest to mark [dagda](https://github.com/eliasgranderubio/dagda) as unmaintained for the following reasons:
- No new commit since over two years
- 5 new issues (some of them critical bugs) unanswered for the last two years
- 4 open PRs from other users without response from maintainer
- 5 open dependabot PRs

Mark dagda as unmaintained

---

data/tags.yml
data/tools/promformat.yml
data/tools/promval.yml

Fixes https://github.com/analysis-tools-dev/static-analysis/issues/1363

Add promformat

---

data/tools/larastan.yml

Starting with Larastan 2.7.0, the Larastan repository will now be managed under the Larastan organization.

Update larastan.yml to use Larastan Org

---

data/tools/codemodder-java.yml

Adding Codemodder to Java tools

Add Codemodder (Java)

---

data/tools/pylyzer.yml

`make render` modifies both `data/api/tools.json` and `README.md` with unrelated changes. All of the `deprecated: true` fields become `deprecated: null` :shrug:

Add pylyzer

---

data/tools/flint.yml

The [flint++ repository](https://github.com/JossWhittle/FlintPlusPlus) is archived as of August 2023, so mark the tool as deprecated.

Mark flint++ as deprecated

---

data/tools/precaution.yml

Precli (or PrecautionCLI) is another SAST that checks Go, Java, and Python code for security vulnerabilities. A free-to-use CLI is available that covers standard library of each language. Also available is a GitHub Action and GitHub App.

Add Precaution CLI as a SAST

---

data/tools/bandit.yml

Back in 2016, there was a nice podcast interview with the maintainers of Bandit that would be nice to include here.
https://www.pythonpodcast.com/episodepage/bandit-with-tim-kelsey-travis-mcpeak-and-eric-brown

Add podcast about Bandit to its tool metadata

---

data/tools/enre-cpp.yml
data/tools/enre-java.yml
data/tools/enre-py.yml
data/tools/enre-ts.yml

Add four new static analysis tool from [XJTU-ENRE](https://github.com/xjtu-enre) group in GitHub, which are **ENRE-cpp, ENRE-java, ENRE-py, ENRE-ts**.  The related .yml files have been added be added to `data/tools/`, and the `make` command was run to modify the readme file.

Add four new static analysis tool from XJTU-ENRE group in GitHub

---

data/tools/doop.yml

The Doop Framework archived their bitbucket repository and moved their code to github, so the links do not work.

Doop Framework moved their source code to github

---

data/tools/sonarqube-cloud.yml
data/tools/sonarqube-for-ide.yml
data/tools/sonarqube-server.yml

SonarQube rebranding

---

data/tools/codedepends.yml

Even though code depends has not changed in two years (hence the deprecation marker) it is still an important analyzer for the R programming language (more important would be the successor <https://github.com/duncantl/CodeAnalysis> but it does not clear the stars-constraint, which in general is hard to hit as static analysis for R remains heavily underrepresented wrt. other languages).

Add code depends (static analysis for R)

---

data/tools/flowr.yml

As part of my other PRs (#1652, #1653, #1654) I try to improve the coverage of R analyzers within this repository. This (for now, final) PR adds my own tool (if this disclaimer is of importance; it still clears all constraints to be added): flowR. 
flowR provides novel dataflow analyses for R, a program slicer, and integration for VS Code and R studio. 
Should those be added/linked as part of the description?

Add flowR, a slicer and dataflow analyzer for R

---

data/tags.yml
data/tools/wasm-language-tools.yml

Repo: https://github.com/g-plane/wasm-language-tools .
This PR also changed tag "wasm" into a "language" type and corrected the spelling.

Add "wasm-language-tools"

---

data/tools/ast-grep.yml

add ast-grep tool

---

data/tags.yml
data/tools/keploy.yml

Hi,
I've added a new entry for Keploy in the data/tools/keploy.yml.
Keploy is an open-source testing platform that helps developers automate and streamline their testing process.
I believe it would be a valuable addition to the list of tools in the repository and could be of interest to developers looking for open-source testing platforms and AI-driven testing solutions.
Please let me know if you need any more information or if you'd like me to make any changes.
Thanks for your time and consideration!

Add keploy

---

data/tools/malcat.yml

Add Malcat, a hexadecimal editor and disassembler for malware analysis. Supports 50+ file formats, multiple CPU architectures, and includes features like Yara scanning, anomaly detection, and Python scripting.

Add Malcat for binary analysis
