- README.md
PVS-Studio also supports C#. Moved to Multiple Languages.
> Modifying PVS-Studio entry.

- README.md
Added a Contents for more readable. :)
> Added Contents

- README.md
> Added a Haskell static analysis tool

- README.md
> Set Python prospector link

- README.md
I have added a software design quality assessment tool Designite.
> added Designite

- README.md
Not sure why Atom decided to clean up spaces at end of lines but there really is only one line change to add the Flint++ tool
> add Flint++

- README.md
> Added scsslint and a CSS category

- README.md
> Added checkmake and new Build tools category

- README.md
added some css stats / metric tools
> added my fav css tools

- README.md
https://github.com/Yelp/undebt
> Adds Yelp/Undebt

- README.md
One more tool for an awesome list
> Added Php Inspections (EA Extended) to list of PHP SCATs

- README.md
Quick note for .NET Analyzer: In Roslyn, Code Fixes are refactoring action.
> Add Roslyn Security Guard

- README.md
> adding adacore analyzer

- README.md
Added three java static analysis tools
> Java: Checker Framework, OWASP Dependency Check and SonarQube

- README.md
Checkout https://github.com/jmolivas/phpqa
I am aware that this project is not OSS yet. License pull request is ongoing: https://github.com/jmolivas/phpqa/pull/36
And i am aware that we have already a tool that is named phpqa in the list. But this is a different tool. I informed the author about this. See https://github.com/jmolivas/phpqa/issues/35
> Added phpqa - PHPQA all-in-one Analyzer CLI tool

- README.md
SideCI is an automated code reviewing tool with GitHub. It enables developers to speed up their code review and development cycle to improve productivity without requiring them to spend valuable time.
> Add SideCI

- README.md
Checkout https://github.com/psecio/parse
> Added Parse: A Static Security Scanner

- README.md
I added WAP which is a SAT that detects and corrects input validation vulnerabilities in PHP web applications. It combines source code static analysis and data mining to detect vulnerabilities and predict false positives. I don’t know if you find it interesting, but I definitely do. :-)
> WAP tool from OSWAP

- README.md
> Added CodeSonar by Grammatech

- README.md
This pull request adds [dennis](https://github.com/willkg/dennis/), a set of utilities for working with PO files to ease development and improve quality.
> Added dennis

- README.md
[Spoon](https://github.com/INRIA/spoon) is a library to write your own static analyses and architectural rule checkers for Java. It can be integrated in Maven and Gradle.
> adds Spoon

- README.md
Propose to add https://github.com/vlajos/misspell_fixer.
>  Propose to add misspell fixer 

- README.md
Added pytype to the Python section
> Added pytype to the Python section

- README.md
The second commit (id c588d5a) is for adding "copyright" emoji.
> Add DeepScan to the list of JavaScript

- README.md
Added in entries for Fortify and Synopsys
> Added in Fortify and Synopsys

- README.md
Adding Gamma (mygamma.io) to the list of tools for Multiple languages
> Adding Gamma

- README.md
Hi!
Solidity is the language of Ethereum Blockchain for writing smart contracts.
Solium is a linter for solidity. I am the project's maintainer. It has been active for last 2 years, has a good number of stars and also some [backing](https://blog.ethereum.org/2018/03/07/announcing-beneficiaries-ethereum-foundation-grants/) from ethereum.
Please let me know in case I missed something out.
Thanks for making & maintaining this project :)
> Add language Solidity & linter Solium

- README.md
Hello @mre . Consider please this PR.
> Added Veracode, TsanCode, and Kiuwan to Multiple Languages section

- README.md
> Update misspell fixer name.

- README.md
Hello @mre,
I would like to add i-Code CNES which is a Fortran analysis code checker.
Thanks !
> Add i-Code CNES as Fortran analysis checker.

- README.md
Hello @mre, 
Help me, please, with this situation.  I'm sending new PR, though, it includes the part of the previous PR I've sent to you already. Github says that there are no problems and I don't see any either. But I've added tools to different sections and added a new section for Dlang. What do you think about that?
> Complex Addition of new tools including new section

- README.md
Added https://github.com/btford/write-good.
> Added write-good

- README.md
Added in a RPG static analyzer I have recently come across.
> #156 Added SourceMeter for RPG

- README.md
There are a couple of t-sql specific static analyzers I have come across recently that are good candidates for the list.  I'm not associated in any way with either of them. Just came across them in my own research into the topic.
> Added two t-sql static analyzers

- README.md
Hi!
This adds a linter named [Goodcheck](https://github.com/sideci/goodcheck), which is a *"Regexp based customizable linter"* and written in Ruby.
I'm so happy if you review this and add to this awesome list! 😊 
Thanks.
> Add Goodcheck to multiple language list

- README.md
ClassGraph is useful for static analysis, both for automated class metadata checkers, but also for manual analysis of class graphs, since it can generate class graph visualizations in GraphViz format. (Disclaimer, I am the author.)
> Added ClassGraph

- README.md
Soot is a famous static analysis tool, There is no reason not to include it!
> adding soot

- README.md
details: https://github.com/mgechev/revive
> Add revive to Go

- README.md
Happy merging, thx :-D
#hacktoberfest
> adding cookstyle linter for chef cookbooks

- README.md
The Language ABAP was added with the Tool abapopenchecks, an enhancement for SAP Code inspector
>  Added ABAP Analysis Tool

- README.md
kube-score is a tool that does static code analysis of your Kubernetes object definitions. The output is a list of recommendations of what you can improve to make your application more secure and resilient.
> Add kube-score

- README.md
About reviewdog
- 660 stars
- https://github.com/haya14busa/reviewdog
- https://medium.com/@haya14busa/reviewdog-a-code-review-dog-who-keeps-your-codebase-healthy-d957c471938b
> Add reviewdog

- README.md
About Slither:
- https://github.com/trailofbits/slither
- https://blog.trailofbits.com/2018/10/19/slither-a-solidity-static-analysis-framework/
- Recently open sourced
- 92 stars and growing!
> add slither

- README.md
> Adding Violations Lib #212

- README.md
See https://github.com/Quasilyte/go-consistent
> Added Quasilyte/go-consistent

- README.md
Add the bellybutton ( https://github.com/hchasestevens/bellybutton ) Python linting engine to the Python section.
> Update README.me to add bellybutton

- README.md
Signed-off-by: Christian Haettich <feddischson@gmail.com>
> Adds the include-gardener to C/C++ section

- README.md
See the [blog post](http://neilmitchell.blogspot.com/2017/06/announcing-weeder-dead-export-detection.html) announcing the tool.
> Add Weeder

- README.md
There is SonarQube already, but there is also a cloud version (since 2017).
> Add SonarCloud.io

- README.md
- mkdocs.yml
> Fix formatting and link to homepage

- README.md
Added AWS Labs Cloudformation Linter
> Added AWS Labs Cloudformation Linter

- README.md
> added Codecheker

- README.md
Three R programming tools were added. Each tool was released on either GPL-3 or
MIT license.
> add R tools: styler, goodpractice, cyclocomp

- README.md
Hi @mre 👋 
I propose we add [qulice](https://www.qulice.com/) to the Java section.
> add qulice

- README.md
Added tool for reformatting Java code into Google style.
> Google Java Reformat

- README.md
- Add [markdownlint](https://github.com/DavidAnson/markdownlint) (Node.js -based tool) to the list
- Fix a few tiny typography issues
> Add markdownlint

- README.md
add dependency analyse tool - depends
> add dependency analyse tool - depends

- README.md
I use Terrascan for work, it's quite nice at detecting some configuration mistakes, and figured it would be a useful addition here.
> added terrascan, a Terraform linter/scanner

- README.md
RIPS is no longer open source.
> Add copyright notice to RIPS

- README.md
Railroader is an open source static analysis security vulnerability scanner for Ruby on Rails applications.
> Add Railroader

- README.md
[SVF](https://github.com/SVF-tools/SVF) a static tool that enables scalable and precise interprocedural dependence analysis for C and C++ programs. SVF also implements some common checker like  MemoryLeakChecker or SourceSinkChecker.
> add SVF for c and c++

- README.md
Add [code inspector](https://www.code-inspector.com) in the list of tools for code quality analysis and technical debt management.
> Add code inspector

- README.md
LDRA is a mature tool suite that includes static analysis that has been in use within the defense & safety critical industries for many years. (I have used it extensively and it is really good if pricey).
> Add LDRA to C/C++ Static Analysis

- README.md
Adds new section for static syntax analysis tools for Tcl language.
Thanks.
> added static syntax analysis tools for Tcl-lang

- README.md
ABAP to upper case, add abaplint
> ABAP to upper case, add abaplint

- README.md
See https://github.com/alexkohler/nargs
> Adds alexkohler/nargs (Go)

- README.md
Wily is a Python tool for running code complexity metrics over every revision
in your git history and tracking changes in complexity over time. It meets the
criteria for addition, as you can see from the following stats:
No. of contributors: 5
GitHub stars: 352
Oldest release on PyPI: 0.4.2 on Oct 15, 2018 (8 months ago)
Wily documentation: https://wily.readthedocs.io/en/latest/
> Add wily to the Python section

- README.md
Adding an awesome new service I came across recently.
> + Codeac.io

- README.md
WhiteHat Security has updated their offer at the start of the year. According to their run of the OWASP benchmark, they are awesome (https://www.whitehatsec.com/blog/benchmarking-accuracy-automated-appsec-testing/). Therefore I believe they should be added to the awesome list.
> Added WhiteHat Application Security Platform

- README.md
[Elm Analyse](https://github.com/stil4m/elm-analyse)
- 5 contributors in last 3 months
- 368 stars on GitHub
- Initially released in February 2017
> add elm-analyse

- README.md
> Repository renamed - link not working

- README.md
https://github.com/classgraph/classgraph
therefore moving it to the multiple languages section.
> Move classgraph to multiple languages

- README.md
> Add notification for CppDepend

- README.md
Fix Insight, Pascal Analyzer, Pascal Expert static analyzers added
> Added section on Delphi.   resolves #254

- README.md
Hi,
I would like to add CodePatrol, a SaaS solution provided by Claranet Cyber Security and geared towards automated security and developer training ([official website](https://cyber-security.claranet.fr/en/codepatrol)).
> Updating list with CodePatrol SaaS solution

- README.md
There were 2 entries for the same app - `staticcheck` from https://github.com/dominikh/go-tools / https://staticcheck.io/. These have been merged.
> Merge duplicate staticcheck entries

- README.md
Signed-off-by: Christian Haettich <feddischson@gmail.com>
> Extend include-gardener information

- README.md
I'm also adding the Protocol Buffer section.
> Add protolint

- README.md
I added 5 Go linters that are also used by the linters aggregator `golangci-lint`.
> Add bodyclose, dogsled, gochecknoglobals, gosimple, wsl

- README.md
PHP Architecture Tester is a static analysis tool to verify architectural requirements.
It provides a natural language abstraction to define your own architectural rules and test them against your software.
> PHP Architecture Tester

- README.md
A terraform static analysis tool to prevent cloud misconfigurations at build time
> Add checkov

- README.md
a lightweight, compliance and security focused, BDD test framework against terraform.
https://terraform-compliance.com
https://github.com/eerkunt/terraform-compliance
> Add terraform-compliance

- README.md
We just ran into using pest for some Erlang code, so adding it to the list as well
> Add pest for Erlang

- README.md
Repo: https://github.com/remarkjs/remark-lint
> Adds remark-lint

- README.md
Since it's abandoned according to its readme.
> Add warning to Java/Huntbugs

- data/data.yml
> Update outdated links (fixes #346)

- data/data.yml
> Add deno_lint

- README.md
> Fix the pfff link

- data/render/src/types.rs
- data/render/templates/README.md
See #382 , #375 for old PRs. Closes #327 .
Now that #381 is done, this can be merged in.
> Parsing star count badge from linters with a Github source field

- README.md
- data/tools.yml
Hi, I found this homepage link is wrong, so i replace it with another one
> Fix homepage of jsonhint

- README.md
- data/tools.yml
I found the source of detekt is a forked repo, so I modified it to the upstream repo
> Modify the source of detekt

- data/tools.yml
Link to project: [https://github.com/returntocorp/semgrep](https://github.com/returntocorp/semgrep)
> Add entry for Semgrep

- data/tags.yml
- data/tools.yml
> Add Github Super-Linter

- README.md
- data/tools.yml
I found that ```Xanitizer``` is duplicate, so I remove one.
> Remove duplicate entry

- data/tools.yml
> Add texlab TeX LSP and linter

- data/tools.yml
> Add PHP Insights

- README.md
- data/tools.yml
`kubeval` was missing from `Containers`, I'd like to see it there as well 👀
> Add kubeval to Containers

- data/tools.yml
Added 'solhint' as another linter for Solidity
> added solhint tool for solidity

- data/tools.yml
es6-plato allows for generating static code analysis for arrow functions.
> Added es6-plato.

- data/tools.yml
> Add ShiftLeft Scan (fixes #345)

- data/tools.yml
Source: https://www.thirtythreeforty.net/posts/2020/05/hacking-reolink-cameras-for-fun-and-profit/
> Add tools for static binary analysis

- data/tools.yml
As discussed with @codecholeric.
> Add ArchUnitNET by @TNG

- data/tools.yml
> Add Pysa for Python by Facebook

- data/tools.yml
> Add brittany Haskell source code formatter

- data/tools.yml
Hello :wave: 
I'm adding `elm-review` to the list.
> Add elm-review

- data/tools.yml
> Add C2Rust, which supersedes Corrode

- data/tools.yml
Adding [TypeScript Call Graph](https://github.com/whyboris/TypeScript-Call-Graph), a CLI tool to generate an interactive graph of functions and calls from your TypeScript files 😎 
Thank you for this excellent collection of tools 🙌 
ps - sorry for auto-formatting the spaces and tabs at the end of some lines in this file 😅
> TypeScript Call Graph CLI tool

- README.md
- data/tags.yml
- data/tools.yml
Some missing Dart, Julia, and security analysis tools I found. 
Related to #504
> Add more tools for Dart, Julia, and Security

- data/tools.yml
> Add security tag to SAST tools

- data/tools.yml
> Add clj-kondo

- data/tools.yml
thanks for checking my PR
Best regards Michiel Cuijpers
> Adding Better Code Hub BCH

- data/tags.yml
- data/tools.yml
Hi 👋 thanks for this awesome project.
In this pr I've added two related SAST tools:
- https://github.com/ConsenSys/mythril
- https://mythx.io
Let me know if there is okay like this 👌
> Add mythril and mythx analysis tools

- data/tools.yml
> Add iblessing for iOS

- data/tools.yml
> Add rust-audit

- data/tools.yml
> Add Prusti for Rust

- data/tools.yml
> Add new entry for Lumnify

- data/tools/clazy.yml
> Add KDE's clazy

- .github/pull_request_template.md
- CONTRIBUTING.md
> Update contribution guide

- data/tools/inspectortiger.yml
> Add InspectorTiger for Python

- data/tools/wala.yml
> Add resource for wala

- data/tools/codacy.yml
> Add resources section for codacy

- data/tools/cppcheck.yml
Hi,
I found this article in one of our sponsor's website, and I think it might be a good way to advertise(?) for them? 
@mre  what do you think?
> Add resource for cppcheck

- .github/workflows/ci.yml
- Makefile
> Skip deprecation check on PR

- .github/workflows/render.yml
> Dispatch rebuilding website event after update

- data/tools/pylint.yml
> Add resource for pylint

- data/tools/mythril.yml
> Add resources to mythril

- data/tools/nauz-file-detector.yml
> Added nauz-file-detector.yml

- data/tools/ghidra.yml
> Add resource for ghidra

- data/tools/mythx.yml
> Extend MythX entry

- data/tools/bloaty.yml
> Add bloaty, a size profiler for binaries

- data/render/templates/README.md
- data/tools/nu-html-checker.yml
- data/tools/standard-ruby.yml
Hi @mre,
I found [this](https://github.com/collections/clean-code-linters) in github collections, so I add it to `More Collections`, and also add new entries from that list.
I am wondering if it makes sense to contribute a PR to [gihub collection repo](https://github.com/github/explore/blob/master/collections/clean-code-linters/index.md) to include our static-analysis repo?
> Update "More Collection" and add new entries

- data/tools/fasterer.yml
> Add Fasterer

- data/tools/rails_best_practices.yml
> Add rails_best_practices

- data/tools/saikuro.yml
> Add Saikuro

- data/tools/helix-qac.yml
> Add resources for Helix QAC

- data/tools/spectral.yml
> Fixing typo

- data/tools/kubelinter.yml
> Add KubeLinter

- data/tools/haskell-dockerfile-linter.yml
Hey,
just improving the readability a bit - missing a space.
Cheers!
> Missing space

- data/tools/dialyzer.yml
> Add resources for dialyzer

- data/tools/njsscan.yml
> Add njsscan by @ajinabraham

- data/tools/pycodequal.yml
Adding PyCodeQual, my SaaS product :-)
> Add PyCodeQual.

- data/tools/errwrap.yml
> Add errwrap by @faith

- data/tools/cargo-expand.yml
> Add cargo-expand by @dtolnay

- data/tools/cargo-udeps.yml
> Add cargo-udeps by @est31

- data/tools/typl.yml
> Add TypL by @getify

- data/tools/vetur.yml
> Update homepage and add resources

- data/tools/churn-php.yml
Development was picked up again recently 🎉
> Churn PHP is no longer deprecated

- README.md
- data/render/templates/README.md
> Fix formatting of "other" category

- data/tags.yml
- data/tools/mega-linter.yml
Added [Mega-Linter](https://nvuillam.github.io/mega-linter/) in the list
There were missing tags so I added them too :)
> Add Mega-Linter + language & formats tags

- data/tools/astre.yml
> Update description of tool 'Astree'.

- data/tags.yml
- data/tools/enlightn.yml
We just launched [Enlightn](https://github.com/enlightn/enlightn), a static and dynamic analysis tool for Laravel apps that helps improve performance, security and code reliability. We launched it 2 days ago, currently has 124 ⭐. Hope you'll consider it!
> Add Enlightn to the list

- data/tools/kics.yml
> Adding KICS in Configuration Management

- data/tools/azsk.yml
The AzSK has a number of feature, but the many feature is the ability to run static infrastructure security testing as part of a CI pipeline.
> Adding Secure DevOps Kit for Azure (AzSK)

- data/tools/mythx.yml
Hi, 
long time no see haha, I guess we are not using `proprietary: true` anymore?
> Remove deprecated key

- data/tools/mdformat.yml
Adding [mdformat](https://github.com/executablebooks/mdformat) Markdown formatter.
> Add mdformat

- data/tags.yml
Hi, 
I guess we are using alphabetical order in `tags.yml`?
> Sort data/tags.yml by alphabetical order

- data/tools/dart-code-metrics.yml
Dart Code Metrics is a static analysis tool that helps developers analyse and improve their Dart code quality.
- Reports code metrics
- Provides additional rules for the dart analyzer
- Checks for anti-patterns
> Add Dart Code Metrics

- data/tools/zpa.yml
Z PL/SQL Analyzer (ZPA) is an extensible code analyzer for PL/SQL and Oracle SQL.
> Add Z PL/SQL Analyzer (ZPA)

- data/render/templates/README.md
> Sort other lists; add owasp

- data/tools/typos
> Add typos tool

- data/tools/scorecard.yml
Hi, 
found this interesting tool recently, so I added an new entry for it.
> Add new entry for scorecard

- data/tools/larastan.yml
> Fix typo in larastan homepage url

- data/tools/shisho.yml
> Add shisho

- data/tools/teamscale.yml
> Update teamscale website and resources

- README.md
- data/render/templates/README.md
- data/tools/diktat.yml
- Fix https://github.com/analysis-tools-dev/static-analysis/issues/866
- Fix https://github.com/analysis-tools-dev/static-analysis/issues/869
- Fix https://github.com/analysis-tools-dev/static-analysis/issues/870
- Fix https://github.com/analysis-tools-dev/static-analysis/issues/872
> Fix `Link Checker` issues

- data/tools/structslop.yml
See https://github.com/orijtech/structslop
> Adding orijtech/structslop: Recommends struct field rearrangements to provide for maximum space/allocation efficiency

- data/tools/weggli.yml
> Add weggli

- README.md
- data/render/src/lib.rs
> Make renderer ignore non-language tags for groups

- data/tools/kubeval.yml
> Add missing tags for kubeval

- data/tools/putout.yml
Hi, thank you for such a useful project!
Just added 🐊`Putout` code transformer.
> Added `🐊Putout` code transformer

- data/tools/sqlvet.yml
> Add sqlvet

- data/tools/diktat.yml
> diktat moved to new homepage

- data/render/templates/README.md
> Use em dashes before description

- data/tools/scanmycode.yml
Adding Scanmycode and Scanmycode CE (Community Edition)
> Adding Scanmycode and Scanmycode CE (Community Edition)

- data/tools/better-code-hub.yml
- data/tools/codacy.yml
- data/tools/codefactor.yml
- data/tools/codescene.yml
- data/tools/codiga.yml
- data/tools/deepscan.yml
- data/tools/deepsource.yml
- data/tools/embold.yml
- data/tools/intellij-idea.yml
- data/tools/mythx.yml
- data/tools/ndepend.yml
- data/tools/nitpick-ci.yml
- data/tools/ocular.yml
- data/tools/pycodequal.yml
- data/tools/reshift.yml
- data/tools/rudra.yml
- data/tools/scrutinizer.yml
- data/tools/sider.yml
- data/tools/sonarcloud.yml
- data/tools/sonatype.yml
- data/tools/sourcemeter.yml
- data/tools/teamscale.yml
- data/tools/trunk.yml
Some projects offer free plans for OSS products or for small projects.
This PR adds this information for paid/proprietary tools who do.
> Add free and oss plans

- data/tools/threatmapper.yml
> Add ThreatMapper static analysis tool for runtime workloads

- data/tools/tca.yml
> Add TencentCodeAnalysis

- data/tools/sigrid.yml
> Add Sigrid

- data/tools/svace.yml
> added link to Svace

- data/tools/goblint.yml
> Add Goblint

- .github/workflows/ci.yml
...unless the change comes from one of the maintainers
> Prevent README.md from getting changed

- data/tools/fixinator.yml
Fixinator is a source code analysis tool for ColdFusion.
> Add Fixinator Tool

- data/render/templates/README.md
> Update to semgrep logo

- data/tools/open-static-analyzer
Add OpenStaticAnalyzer tool info which can be found at [https://github.com/sed-inf-u-szeged/OpenStaticAnalyzer](https://github.com/sed-inf-u-szeged/OpenStaticAnalyzer)
> Add OpenStaticAnalyzer tool info

- data/tools/mypy.yml
> Add video resources to mypy

- data/tools/codeql.yml
> Add video resources for CodeQL

- data/tools/deepsource.yml
> Add video resources to deepsource

- data/tools/clippy.yml
> Clippy video resources

- data/tools/psalm.yml
> Psalm video resources

- data/tools/rubocop.yml
> Add video resources to Rubocop

- data/tools/flake8.yml
> Add more video resources for flake8

- data/tools/staticcheck.yml
> Add video resources for staticcheck

- data/tools/kubeconform.yml
> Add kubeconform

- data/tools/super-linter.yml
> Add video for Github Super Linter

- data/tools/semgrep.yml
> Add semgrep video resources

- data/tools/sigrid.yml
> Update sigrid resources

- data/tools/enlightn.yml
> Add video resource for englithn

- data/tools/understand.yml
> Add resources for understand

- data/tools/refurb.yml
> Add refurb by @dosisod

- data/tools/codiga.yml
> Add video resources for codiga

- data/tools/htmlbeautifier.yml
Hi @mre,
Could you consider this as part of hacktoberfest by adding `hacktoberfest-accepted` label?
> Add htmlbeautifier

- data/tools/metric_fu.yml
> Add MetricFu

- data/tools/emerge.yml
Added emerge to the list of tools
* [x ] I have not changed the `README.md` directly.
> Add emerge

- data/tools/chart-testing.yml
- data/tools/clusterlint.yml
- data/tools/datree.yml
- data/tools/kube-lint.yml
- data/tools/kube-linter.yml
- data/tools/kube-score.yml
- data/tools/kubeconform.yml
- data/tools/kubelinter.yml
- data/tools/kubeval.yml
> Remove additional tags for kubernetes-specific tools

- data/tools/autocorrect.yml
https://github.com/huacnlee/autocorrect
> Add AutoCorrect

- data/tools/codeque.yml
> Add CodeQue - structural code search for JS and TS

- data/tools/perlanalyzer.yml
> Add `Perl::Analyzer`

- data/tools/diffblue.yml
> Add Diffblue

- data/tools/yapf.yml
> Add YAPF for Python

- data/tools/autopep8.yml
> Add autopep8

- data/tools/google-java-format.yml
> Extend google-java-format

- data/api/tools.json
- data/render/src/lib.rs
- data/render/src/types.rs
- data/tools/black.yml
- data/tools/codecov.yml
- data/tools/codescene.yml
- data/tools/codiga.yml
- data/tools/deepsource.yml
- data/tools/eslint.yml
- data/tools/mega-linter.yml
- data/tools/mypy.yml
- data/tools/phpstan.yml
- data/tools/psalm.yml
- data/tools/semgrep.yml
- data/tools/sigrid.yml
- data/tools/sonarqube.yml
> Add reviews and demos

- data/tools/trustinsoft.yml
<!--
👋 Thank you for your contribution!
Please make sure to check all of the items below.
- 🚨 New tools have to be added to `data/tools/`
> Add TrustInSoft Analyzer

- data/tools/perltidy.yml
> Add perltidy

- data/tools/codesee.yml
> Add codesee

- data/tools/StaticReviewer
- data/tools/staticreviewer.yml
> make render

- README.md
- data/api/tools.json
- data/render/src/types.rs
- data/tools/clayton.yml
- data/tools/pyupgrade.yml
- data/tools/redex.yml
> Enforce and fix category types

- data/tools/cargo-call-stack.yml
- data/tools/krane.yml
- data/tools/mariana-trench.yml
- data/tools/reflection.yml
- data/tools/steady.yml
> Add more tools

- data/api/tools.json
- data/tools/clang-tidy.yml
- data/tools/code-cracker.yml
- data/tools/codeburner.yml
- data/tools/codepeer.yml
- data/tools/cppcheck.yml
- data/tools/electrolysis.yml
- data/tools/frama-c.yml
- data/tools/fsharplint.yml
- data/tools/goodpractice.yml
- data/tools/haxe-checkstyle.yml
- data/tools/jsprime.yml
- data/tools/mondrian.yml
- data/tools/php-refactoring-browser.yml
- data/tools/retirejs.yml
- data/tools/spoon.yml
- data/tools/svf.yml
- data/tools/test.yml
- data/tools/veracode.yml
- data/tools/wap.yml
- data/tools/xcode.yml
This also fixes a few outdated links
> Replaced several http:// links with https://

- data/api/tags.json
- data/api/tools.json
- data/render/src/lib.rs
- data/render/src/types.rs
- data/render/templates/README.md
- data/tags.yml
- data/tools/codeque.yml
- data/tools/emerge.yml
- data/tools/goblint.yml
- data/tools/o360.yml
- data/tools/php_codesniffer.yml
- data/tools/shipshape.yml
- data/tools/staticreviewer.yml
- data/tools/threatmapper.yml
> Rename tag.type to tag.value; fix invalid values

- data/tools/sast-online.yml
Supersedes #1221. I've fixed the license and mentioned the free plan.
@alievinfo fyi
> Add SAST Online

- data/tools/diffrs.yml
> Add diff.rs

- README.md
- data/render/templates/README.md
> Expand language section, not "other" section

- data/tools/bearer.yml
> Add Bearer

- data/tools/fprettify.yml
> Add fprettify

- data/tools/dotnet-format.yml
> Add dotnet-format

- data/tools/sleek.yml
> Add sleek for SQL

- data/tools/rector.yml
> Add rector

- data/tools/lockbud.yml
> Add lockbud for Rust

- data/tools/refactorfirst.yml
* [ x] I have not changed the `README.md` directly.
> Adding refactorfirst.yml

- data/tools/flakeheaven.yml
- data/tools/textlint.yml
> Add textlint and flakeheaven

- data/tools/goast-rego.yml
- data/tools/goast.yml
- data/tools/oxc.yml
> Add goast and oxc

- data/tools/cakefuzzer.yml
I added our interactive application security testing tool called CakeFuzzer. CakeFuzzer employs both static and dynamic testing techniques to find all possible endpoints of the application and conduct security tests.
> Adding a new tool called CakeFuzzer

- README.md
- data/api/tools.json
- data/tools/Meziantou.Analyzer.yml
- data/tools/SonarAnalyzer.CSharp.yml
I didn't commit [Commit list](https://github.com/analysis-tools-dev/static-analysis/pull/1421/commits/44f80e2bedea71c38908cd628d8ddff31818224c)!
> Add Meziantou and SonarAnalyzer.CSharp analyzer

- data/tools/openrewrite.yml
> Add OpenRewrite tool

- data/tools/bugprove
- data/tools/bugprove.yml
> Add BugProve static analyser

- data/tools/checker-framework.yml
> Expand description of the Checker Framework

- data/render/templates/README.md
> Fix some broken internal link in the Readme

- data/tools/dataflow-framework.yml
> Add the Dataflow Framework tool

- data/tools/pgspot.yml
> Add pgspot

- data/tools/arkitect.yml
> Add PHPArkitect

- data/tools/codemodder-python.yml
Adding Codemodder to Python tools
> Add Codemodder (Python)

- data/tools/pixee.yml
Adding Pixee(and Pixeebot) to Java tools
> Add Pixee (Java)

- data/tools/cargo-geiger.yml
p.s. added this list to [Awesome-Awesome List](https://github.com/RustAU/Awesome-Awesome) :)
> Add cargo-geiger (Rust)

- README.md
- data/api/tools.json
- data/tools/cargo-unused-features.yml
- data/tools/chart-testing.yml
- data/tools/pyupgrade.yml
> all: fix some comments

- data/tools/freeplane-code-explorer.yml
* [ x] I have not changed the `README.md` directly.
> Add link to Freeplane Code Explorer

- data/tools/vera.yml
> Mark vera++ as deprecated

- data/tools/codety.yml
> Add codety.yml

- data/tools/codety.yml
Update codety.yml for fixing the failed pipeline.
> Update codety.yml for fixing the failed pipeline. 

- data/tools/fantomas.yml
- data/tools/ionide-analyzers.yml
> Add F# tools Fantomas and ionide-analyzers

- data/tools/zpa.yml
Update homepage and description of ZPA.
> Update ZPA metadata

- data/tools/derscanner.yml
> Add DerScanner

- data/tools/r-language-server.yml
The R language server is an actively developed LSP implementation for the R programming language.
> Add the R language server

- data/tools/fortitude.yml
> Add Fortitude

- data/tools/enforster.yml
Added Enforster AI in SAST tools
> Added Enforster AI

- data/tools/database_consistency.yml
Hi @mre, I’m back for this year’s Hacktoberfest 😀
Please check this one out. More are coming.
> Add DatabaseConsistency

- data/tools/traceroute.yml
> Add Traceroute

- data/tools/erb-formatter.yml
> Add ERB Formatter
